### ISSUE TITLE
ARDUINO SDCARD / POLYDOS

### ISSUE THREAD

**Issue by bluebell12** [nealcrook/nascom#3]
Hi Neil,  

Earlier this month I remembered the box in the loft containing the Nascom 2, Memory Card & AVC that my Dad bought for us 40+ years ago.  I doubt it had been powered up since the mid-80s when the BBC micro and then IBM PC arrived.   Unsurprisingly it did not work but I am well on the way to getting the main board operational - a few 74 devices were not working and the video and IO PROMs were dead (just waiting for some replacements to program).   Amazing how much I can remember about the NASCOM after so long! And surprised to find so many other people who have some enthusiasm for it.

While I was waiting for parts I was thinking about building a solid-state store based on a Netduino that I had lying around but then I stumbled on your Arduino / POLYDOS solution.   I noticed that you say you might have a spare PCB and could supply the POLYDOS EPROM.   I would like to get hold of these if possible.  Also after a NASSYS3 ROM.  I can get loan of a DATAMAN 48PRO which I will use to blow the Video and IO PROMS so could do the EPROMs myself at the same time if necessary.  Happy to send parts / transfer money in whatever combination works best.     

Thanks for any help you can provide.

David Robinson
david@bluebell12.co.uk

**Comment by nealcrook** [comment]
Dave and I communicated and I supplied a PCB, closing.
